import type { NextPage } from "next";
import Head from "next/head";

import { Header } from "../components";
import { Dashboard } from "../sections";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fintech App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Dashboard />
    </>
  );
};

export default Home;
